apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicedna-agent.fullname" . }}
  labels:
    {{- include "servicedna-agent.labels" . | nindent 4 }}
data:
  collector.yaml: |
    {{- .Files.Get "files/collector.yaml" | nindent 4 }}
