apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicedna-agent.fullname" . }}
  labels:
    {{- include "servicedna-agent.labels" . | nindent 4 }}
data:
  collector.yaml: |
    {{- .Files.Get "files/collector.yaml" | nindent 4 }}
  {{- if .Values.kubernetesMetadata.enabled }}
  collector-kubernetes.yaml: |
    {{- .Files.Get "files/collector-kubernetes.yaml" | nindent 4 }}
  {{- end }}
