{{- if not .Values.servicedna.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicedna-agent.fullname" . }}
  labels:
    {{- include "servicedna-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  servicedna-key: {{ required "servicedna.key (or servicedna.existingSecret) is required" .Values.servicedna.key | quote }}
{{- end }}
