apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicedna-agent.fullname" . }}
  labels:
    {{- include "servicedna-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "servicedna-agent.selectorLabels" . | nindent 4 }}
  ports:
    - {name: otlp-grpc, port: 4317, targetPort: otlp-grpc}
    - {name: otlp-http, port: 4318, targetPort: otlp-http}
    - {name: zipkin, port: 9411, targetPort: zipkin}
